// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscmlpgmasjsmqjgnzyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY21scGdtYXNqc21xamduenl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MTA0NjgsImV4cCI6MjA4NzI4NjQ2OH0.grI04IrR5NheDmx81T-N-p2y6ScsjJXj8SLk98tLMoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});